name: ci

on:
  push:
    branches:
      - 'master'

env:
  JENKINS_VERSION: 2.401.2

jobs:
  Build-and-Push-Container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ secrets.ETHERSYS_GHCR_USER }}
          password: ${{ secrets.ETHERSYS_GHCR_PASS }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          build-args: JENKINS_VERSION=${{ env.JENKINS_VERSION }}
          push: true
          tags: ghcr.io/ethersys/jenkins:latest,ghcr.io/ethersys/jenkins:${{ env.JENKINS_VERSION }}
